-- migration: create ai_reports table
-- description: stores history of weekly ai-generated financial summary reports
-- affected objects: ai_reports table
-- special considerations: jsonb content structure for flexible report data

-- create ai_reports table to store ai-generated financial insights
-- this table archives weekly reports containing cashflow summaries, forecasts, and insights
create table ai_reports (
  -- unique identifier for the report record
  id uuid primary key default gen_random_uuid(),
  
  -- foreign key to companies table
  -- cascading delete removes all reports when company is deleted
  company_id uuid not null references companies(id) on delete cascade,
  
  -- report content in json format
  -- structure includes: week dates, financial summary, forecast, and insights
  -- example: {"week_start_date": "2025-10-06", "summary": {...}, "forecast": "...", "insights": [...]}
  content jsonb,
  
  -- timestamp when the report was generated by the ai service
  generated_at timestamptz not null default now()
);

-- enable row level security on ai_reports table
-- ensures users can only access reports belonging to their company
alter table ai_reports enable row level security;

-- rls policy: allow authenticated users to read their company's reports
-- rationale: users need to view historical ai-generated reports
create policy "allow authenticated users to select own ai reports"
on ai_reports for select
to authenticated
using (company_id = get_my_company_id());

-- rls policy: allow anonymous users to read their company's reports
-- rationale: supports public dashboard scenarios if needed
create policy "allow anonymous users to select own ai reports"
on ai_reports for select
to anon
using (company_id = get_my_company_id());

-- rls policy: allow authenticated users to create reports for their company
-- rationale: allows manual report generation or ai service to create reports
create policy "allow authenticated users to insert own ai reports"
on ai_reports for insert
to authenticated
with check (company_id = get_my_company_id());

-- rls policy: allow authenticated users to delete their company's reports
-- rationale: users may want to remove old or incorrect reports
create policy "allow authenticated users to delete own ai reports"
on ai_reports for delete
to authenticated
using (company_id = get_my_company_id());

-- create index on company_id for efficient filtering by company
create index idx_ai_reports_company_id on ai_reports(company_id);

-- create index on generated_at for chronological sorting and date-range queries
create index idx_ai_reports_generated_at on ai_reports(generated_at);

-- create index on (company_id, generated_at) for efficient company-specific report retrieval
create index idx_ai_reports_company_generated on ai_reports(company_id, generated_at desc);
